
package vn.easycredit.fis.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Services", targetNamespace = "http://api.esigncloud.mobileid.vn/")
//@XmlSeeAlso({
//    ObjectFactory.class
//})
public interface Services {


    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prepareFileForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareFileForSignCloud")
    @ResponseWrapper(localName = "prepareFileForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareFileForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/prepareFileForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/prepareFileForSignCloudResponse")
    public SignCloudResp prepareFileForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorizeHashSigningForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.AuthorizeHashSigningForSignCloud")
    @ResponseWrapper(localName = "authorizeHashSigningForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.AuthorizeHashSigningForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/authorizeHashSigningForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/authorizeHashSigningForSignCloudResponse")
    public SignCloudResp authorizeHashSigningForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCertificateDetailForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.GetCertificateDetailForSignCloud")
    @ResponseWrapper(localName = "getCertificateDetailForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.GetCertificateDetailForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/getCertificateDetailForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/getCertificateDetailForSignCloudResponse")
    public SignCloudResp getCertificateDetailForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "regenerateAuthorisationCodeForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.RegenerateAuthorisationCodeForSignCloud")
    @ResponseWrapper(localName = "regenerateAuthorisationCodeForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.RegenerateAuthorisationCodeForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/regenerateAuthorisationCodeForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/regenerateAuthorisationCodeForSignCloudResponse")
    public SignCloudResp regenerateAuthorisationCodeForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "regenerateAuthorizationCodeForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.RegenerateAuthorizationCodeForSignCloud")
    @ResponseWrapper(localName = "regenerateAuthorizationCodeForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.fis.ws.RegenerateAuthorizationCodeForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/regenerateAuthorizationCodeForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/regenerateAuthorizationCodeForSignCloudResponse")
    public SignCloudResp regenerateAuthorizationCodeForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prepareRenewCertificateForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareRenewCertificateForSignCloud")
    @ResponseWrapper(localName = "prepareRenewCertificateForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareRenewCertificateForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/prepareRenewCertificateForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/prepareRenewCertificateForSignCloudResponse")
    public SignCloudResp prepareRenewCertificateForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prepareChangeCertificateForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareChangeCertificateForSignCloud")
    @ResponseWrapper(localName = "prepareChangeCertificateForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareChangeCertificateForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/prepareChangeCertificateForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/prepareChangeCertificateForSignCloudResponse")
    public SignCloudResp prepareChangeCertificateForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prepareRevokeCertificateForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareRevokeCertificateForSignCloud")
    @ResponseWrapper(localName = "prepareRevokeCertificateForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareRevokeCertificateForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/prepareRevokeCertificateForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/prepareRevokeCertificateForSignCloudResponse")
    public SignCloudResp prepareRevokeCertificateForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadFileForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.DownloadFileForSignCloud")
    @ResponseWrapper(localName = "downloadFileForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.DownloadFileForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/downloadFileForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/downloadFileForSignCloudResponse")
    public SignCloudResp downloadFileForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorizeSingletonSigningForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.AuthorizeSingletonSigningForSignCloud")
    @ResponseWrapper(localName = "authorizeSingletonSigningForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.AuthorizeSingletonSigningForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/authorizeSingletonSigningForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/authorizeSingletonSigningForSignCloudResponse")
    public SignCloudResp authorizeSingletonSigningForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignCertificateForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.AssignCertificateForSignCloud")
    @ResponseWrapper(localName = "assignCertificateForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.AssignCertificateForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/assignCertificateForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/assignCertificateForSignCloudResponse")
    public SignCloudResp assignCertificateForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReceiptForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.GetReceiptForSignCloud")
    @ResponseWrapper(localName = "getReceiptForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.GetReceiptForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/getReceiptForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/getReceiptForSignCloudResponse")
    public SignCloudResp getReceiptForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "declineCertificateForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.DeclineCertificateForSignCloud")
    @ResponseWrapper(localName = "declineCertificateForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.DeclineCertificateForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/declineCertificateForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/declineCertificateForSignCloudResponse")
    public SignCloudResp declineCertificateForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "disableCertificateForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.DisableCertificateForSignCloud")
    @ResponseWrapper(localName = "disableCertificateForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.DisableCertificateForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/disableCertificateForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/disableCertificateForSignCloudResponse")
    public SignCloudResp disableCertificateForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enableCertificateForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.EnableCertificateForSignCloud")
    @ResponseWrapper(localName = "enableCertificateForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.EnableCertificateForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/enableCertificateForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/enableCertificateForSignCloudResponse")
    public SignCloudResp enableCertificateForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifySignedFileForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.VerifySignedFileForSignCloud")
    @ResponseWrapper(localName = "verifySignedFileForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.VerifySignedFileForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/verifySignedFileForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/verifySignedFileForSignCloudResponse")
    public SignCloudResp verifySignedFileForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadFileForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.UploadFileForSignCloud")
    @ResponseWrapper(localName = "uploadFileForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.UploadFileForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/uploadFileForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/uploadFileForSignCloudResponse")
    public SignCloudResp uploadFileForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prepareCertificateForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareCertificateForSignCloud")
    @ResponseWrapper(localName = "prepareCertificateForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareCertificateForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/prepareCertificateForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/prepareCertificateForSignCloudResponse")
    public SignCloudResp prepareCertificateForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorizeCounterSigningForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.AuthorizeCounterSigningForSignCloud")
    @ResponseWrapper(localName = "authorizeCounterSigningForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.AuthorizeCounterSigningForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/authorizeCounterSigningForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/authorizeCounterSigningForSignCloudResponse")
    public SignCloudResp authorizeCounterSigningForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSignedFileForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.GetSignedFileForSignCloud")
    @ResponseWrapper(localName = "getSignedFileForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.GetSignedFileForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/getSignedFileForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/getSignedFileForSignCloudResponse")
    public SignCloudResp getSignedFileForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changePasscodeForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.ChangePasscodeForSignCloud")
    @ResponseWrapper(localName = "changePasscodeForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.ChangePasscodeForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/changePasscodeForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/changePasscodeForSignCloudResponse")
    public SignCloudResp changePasscodeForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "forgetPasscodeForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.ForgetPasscodeForSignCloud")
    @ResponseWrapper(localName = "forgetPasscodeForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.ForgetPasscodeForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/forgetPasscodeForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/forgetPasscodeForSignCloudResponse")
    public SignCloudResp forgetPasscodeForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prepareHashSigningForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareHashSigningForSignCloud")
    @ResponseWrapper(localName = "prepareHashSigningForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.PrepareHashSigningForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/prepareHashSigningForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/prepareHashSigningForSignCloudResponse")
    public SignCloudResp prepareHashSigningForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSignatureValueForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.GetSignatureValueForSignCloud")
    @ResponseWrapper(localName = "getSignatureValueForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.GetSignatureValueForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/getSignatureValueForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/getSignatureValueForSignCloudResponse")
    public SignCloudResp getSignatureValueForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setCertificateDetailForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.SetCertificateDetailForSignCloud")
    @ResponseWrapper(localName = "setCertificateDetailForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.SetCertificateDetailForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/setCertificateDetailForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/setCertificateDetailForSignCloudResponse")
    public SignCloudResp setCertificateDetailForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @param signCloudReq
     * @return
     *     returns vn.com.fis.ws.SignCloudResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "approveCertificateForSignCloud", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.ApproveCertificateForSignCloud")
    @ResponseWrapper(localName = "approveCertificateForSignCloudResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.ApproveCertificateForSignCloudResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/approveCertificateForSignCloudRequest", output = "http://api.esigncloud.mobileid.vn/Services/approveCertificateForSignCloudResponse")
    public SignCloudResp approveCertificateForSignCloud(
        @WebParam(name = "signCloudReq", targetNamespace = "")
        SignCloudReq signCloudReq);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://api.esigncloud.mobileid.vn/", className = "vn.easycredit.fis.ws.GetVersionResponse")
    @Action(input = "http://api.esigncloud.mobileid.vn/Services/getVersionRequest", output = "http://api.esigncloud.mobileid.vn/Services/getVersionResponse")
    public String getVersion();

}
